---
title: 'Article review - Voices from the far right: a text analysis of Swedish parliamentary
  debates'
author: "Stefan Eschenwecker"
date: "22 2 2021"
output: pdf_document
fontsize: 12pt
spacing: double
bibliography: BDAwR.bib
csl: american-political-science-association.csl
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The article of Magnusson et al.[-@magnusson.2018] analyses the response of Swedish mainstream parties to the increasing electoral success of the far-right Sweden Democrats (SD). However, unlike the majority of so far conducted researches, that focus primarily on the content of electoral campaigns or propositions regarding a certain policy, parliamentary debates are the object of investigation in this study. The authors try to elaborate on how the appearance of a mostly single-issue party like the anti-immigrant SD shaped the topics, respectively the narrative of discussions in the plenary hall [@magnusson.2018 2]. Is the relationship between established and new political actors actually characterized by cooperation or by controversy? Do mainstream parties ally against the SD or is there even some sort of assimilation process from one side or another?

The subject of dealing with populist parties on the right political spectrum is contemporary and important. As of today, almost every European country faces the emergence of at least one relevant rightist movement. Therefore, it is essential to scrutinize how the individual political players interact. To contribute to the current strand of research, Magnusson et al. cover every speech held in the *Riksdag* in a period from 1994 up to 2017. While conservative study approaches seem to suffice for certain purposes, this big data concept is not only able to count the frequency of words but to distinguish various frames of political parties regarding an issue, like for example the migration theme.

The theoretical foundation of the paper is twofold: On the one hand, the authors work with a strategy-theory that classifies several distinct ways of coping with new political rivals and, on the other hand, they implement approaches of communications research. According to Meguid, they distinguish between three main strategies. Firstly, mainstream parties could act dismissive. The aim behind this behavior is to marginalize the salience of the challenging group's primary topic and therefore decrease the influence of the party as a whole. Secondly, the old parties could use an adversarial strategy and locate themselves on the opposite side of the single party's issue. However, this could manifest in a new cleavage and even lead to an increase of votes for the opponent. Lastly, the established political actors could behave accommodative towards rivals, diminish their role by taking over the subject of relevance, take advantage of their ruling experience and use their embedded social networks. To ensure the feasibility of this concept for parliamentary debates, Magnusson et al. combine it with the communicational distinction between subjects into both agenda and framing. While the agenda is concerned about what kind of topics are covered and how often, framing digs deeper and emphasizes the meaning behind words and the context of a speech [@magnusson.2018 3f.]. Instead of deductively testing certain hypotheses, the authors follow a rather explorative study design.

The empirical part of the paper starts with a summary of the SD's electoral increase throughout the last two decades, which even lead up to a permanent parliamentary opposition role for the party in the *Riksdag*. Because the SD stresses the negative influence of migration like no other party, this development seems surprising given the steady numbers of people immigrating to Sweden. Only during the worldwide migration movement in 2015, the number of migrants in Sweden rapidly jumped to about 160,000 per year, which had been almost five times higher than usual (ebd. 5f.). Subsequently, the authors elaborate on the underlying data. As mentioned before, Magnusson et al. scrutinize all parliamentary debates between 1994 and 2017. Overall, approximately 300,000 speeches of 1,500 speakers are included in the project. To clean up this huge amount of tokens, the researchers for example choose to remove stop words or nonpolitical speeches. Furthermore, they categorize the debates into four distinct types and exclude the government-questions. Thus, a corpus of three different categories, with much fewer tokens and distinct words remains (ebd. 7f.). Methodologically, the writers try to combine the benefits of both qualitative and quantitative content analysis. Therefore, a so-called Latent Dirichlet Allocation (LDA) model, which enables the researchers to not only grasp the agenda of the speeches but also assess the underlying frame of a text, is applied. To limit the expanse of the study, the scientists choose to work with *word seeds* and *anchor words*. Inductively, a certain amount of words gets declared as specific for a certain topic, so that the probability of it being used in another circumstance gets reduced to a value of zero. In this case, expressions like *refugee*, *asylum*, and *integration policy* were some of these anchor words. The estimated number of topics is set at 50, although the authors point out that for their purposes it is not important if this number is accurate, as they are mainly interested in a single topic, namely immigration. Additionally, two different indicators get calculated. On the one hand, the frequency of a word in a specific subject is computed by $p(\frac{w}{k})$ and on the other hand, to measure a distinct word count, the probability of a topic for each expression $p(\frac{k}{w})$ gets computed (ebd. 8f.).

By looking at the results of the project, the rapid incline of the immigration policy in party leader debates just after the SD had entered the parliament in 2010, immediately strikes the eye, as much as the downfall after the peak of the worldwide migration movement in the year 2015. However, in subject and interpellation debates, the curve has been relatively steady and only slightly trending upwards since the SD has been part of the in-parliament discussions (ebd. 10f.). Thus, Figure 4 of the paper differentiates between the topic proportion per party and therefore depicts, that almost all other parties in parliament tend to discuss migration almost equally often. While the SD's curve is starting at a much higher scale, it assimilates over time and after 2015 the group talks about the subject not remarkably more often than any other political actor (ebd. 12). A glimpse at the framing of immigration policy offers a similar starting point, as the SD's graph is beginning at a much higher point. Although the framing graph per party also shows a decline of difference between the challenger and the established players, there remains a noticeable gap between them, at least in both party leader and subject debates [@magnusson.2018 14]. In conclusion, the authors argue, that the mainstream parties initially responded to the SD with a dismissive strategy, at least in the interpellation and subject debates. Regarding the party leader speeches, it seems possible, that the high media attention facilitated the salience of the migration topic. Over time, however, the difference in agenda-setting has diminished. When it comes to the framing analysis, more significant effects could be examined: The established parties clearly did not act accommodatively, but used more of a dismissive and adversarial approach, as there is still a clear distinction between the SD and all other parties possible (ebd. 15).

Two positive aspects can be stated about this study: Firstly, the authors are very transparent, as they include a link to their original data corpus in the paper, and secondly, they try to fulfill all criteria of proper quantitative research, namely objectivity, reliability, and validity, by e.g. testing their model with another topic (energy policy), using a different amount of estimated debate subjects and adding, respectively changing some of the anchor words. This indicates, that the results are as solid as they can get in social science. However, one could criticize that Magnusson et. al only showed three distinct words in Table 4 (ebd. 13). It would be desirable if the authors incorporated more expressions, because *migration minister* is also used by most of the other parties and the remaining ones are simply names of government personnel, that occupy a leading role in immigration policy. In this case, it is not unusual for an opposition party to sharply criticize the governing majority. To put it in another way, there is no sign, at least within the content of Table 4, that the SD for instance framed immigration as a danger to Sweden, in contrast to established parties probably referring to immigration as a chance.

Altogether, the article of Magnusson et al. is an excellent example of how to integrate the benefits of big data into social science. Concerning the list of advantages and disadvantages of new data by Salganik [-@salganik.2018 17-41], it obviously stands out that the paper profits from the size of the data. Through big data, the authors were able to scrutinize over 300,000 speeches [@magnusson.2018 7]. Common qualitative and quantitative content analysis would have resulted in unmanageable effort and expenditure. Additionally, the corpus is nonreactive since the Swedish state simply uploads objective protocols from parliamentary debates. The fact that the data is not always-on, because it takes time to write protocols and publish them on a state website is not a pitfall for there is not a parliamentary meeting every other minute. Magnusson et al. also take care of most of the potential biases caused by big data. Therefore, they apply a data set that is freely accessible for everybody. Furthermore one could assume that the Swedish administration provides a complete collection of parliamentary protocols. An algorithmic confounding seems impossible as well as a general drift of the corpus because from the beginning to the end only speeches of elected delegates are considered. Lastly, the data set is not sensitive since parliamentary debates are usually held publicly to present and argue about different political opinions. However, the authors had to deal with two pitfalls of a big data analysis. On the one hand, the number of speeches is not perfectly representative, considering that a share of only 20 percent of representatives accounted for nearly 65 percent of the entire contributions (ebd. 7). On the other hand, an amount of over 101 million *dirty* tokens had to be cleaned up (ebd. 7f.). It goes without saying that the scientists had to implement a lot of simplifying assumptions and subjectively rule out an enormous amount of tokens when it came to cleaning the corpus. Nevertheless, by being transparent and testing their model under different conditions and variables, the authors were able to successfully combine the benefits of both common and new big data content analysis in such a manner that this paper can act as a role model for further surveys.

\pagebreak

# References
